### ISSUE TITLE
QSM Explorer example

### ISSUE THREAD

**Issue by lmyreg2017** [homalg-project/ToricVarieties_project#134]
Suggestion:

- Add one more command -- LoadPackage( "QSMExplorer" ); at the beginning of each example file.
- Recheck the input, shall we keep purely loopwise closed diagrams or allowed diagrams with external legs?

**Comment by HereAround** [comment]
@lmyreg2017  Does https://github.com/homalg-project/ToricVarieties_project/pull/156 address all of this?

**Comment by lmyreg2017** [comment]
@HereAround Yes, my issues are fully addressed in #156, thanks!

**Comment by HereAround** [comment]
Ok. I close this then.
