### ISSUE TITLE
Remove JuliaEvalString

### ISSUE THREAD

**Issue by HereAround** [homalg-project/ToricVarieties_project#140]
As suggested by @fingolfin in https://github.com/oscar-system/JToric.jl/pull/38:

> Another thing: I noticed that in JConvex, you use JuliaEvalString a lot. That's inefficient and should almost never be necessary. It also leads to hard to debug code.
> For example, if one defined pm as in https://github.com/oscar-system/JToric.jl/issues/40, then this works just fine in GAP: pm.polytope.Polytope()

**Comment by fingolfin** [comment]
This can be closed now as we have https://github.com/oscar-system/JToric.jl/issues/73
