### ISSUE TITLE
Make TopcomInterface optional in tests

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/ToricVarieties_project#148]
The new tests in 368614efaf4e44ed8edfd0c64558ef82bfe3e32a require TopcomInterface, which in turn requires TOPCOM, which is not available on our CI server. Could you wrap the tests in a suitable `if` block which tests if TopcomInterface is available? Here is an example of such an `if` block (in FinGSetsForCAP testing if FinSetsForCAP is available): https://github.com/homalg-project/FinGSetsForCAP/blob/master/examples/ReconstructGroup.g#L10-L18

**Comment by HereAround** [comment]
This should be fixed with https://github.com/homalg-project/ToricVarieties_project/commit/c50b3b88e2163ec439331b821c9a6b2be9cd9e6f. Can you confirm?

**Comment by zickgraf** [comment]
Yes, fixed! Thanks!
