### ISSUE TITLE
Can't pick up ToricVarieties release - wrong date in the release tag

### ISSUE THREAD

**Issue by olexandr-konovalov** [homalg-project/ToricVarieties_project#169]
Hi, I see in check for updates logs:
```
[/circa/home/gap-jenkins/pkgadmin/pkgcache/toricvarieties/tmp/ToricVarieties.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /circa/home/gap-jenkins/pkgadmin/pkgcache/toricvarieties/tmp/ToricVarieties.zip or
        /circa/home/gap-jenkins/pkgadmin/pkgcache/toricvarieties/tmp/ToricVarieties.zip.zip, and cannot find /circa/home/gap-jenkins/pkgadmin/pkgcache/toricvarieties/tmp/ToricVarieties.zip.ZIP, period.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ToricVarieties.zip or
        ToricVarieties.zip.zip, and cannot find ToricVarieties.zip.ZIP, period.
```
and then 
```
* ToricVarieties - new version 2021.09.05 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/homalg-project/ToricVarieties_project/releases/download/2\
021-09-05/ToricVarieties[ ".zip" ]
  unpacking ToricVarieties.zip
Archive:  ToricVarieties.zip
ERROR (ToricVarieties): could not unpack archive .... SKIPPING !!!
```
The link above is 

https://github.com/homalg-project/ToricVarieties_project/releases/download/2021-09-05/ToricVarieties.zip 

and opening it shows "Not Found". 

Now I see what's happening. Going to https://github.com/homalg-project/ToricVarieties_project/releases/tag/2021-09-95 and checking the link to `ToricVarieties.zip` and copying link address shows _almost_ the same link:

https://github.com/homalg-project/ToricVarieties_project/releases/download/2021-09-95/ToricVarieties.zip

except that the date is the 95th of September! Please fix this!

**Comment by HereAround** [comment]
@alex-konovalov 

Thank you for pointing out this issue! Indeed, it seems that I made an unfortunate typo in the release tag, which then lead to this strange date. I have fixed this.

I have used this opportunity to create a new release. You should be able to pick up the latest version of `ToricVarieties`:
https://github.com/homalg-project/ToricVarieties_project/releases/download/2021-11-17/ToricVarieties.zip

Please let me know if the issue remains. Thank you!

**Comment by olexandr-konovalov** [comment]
@HereAround thanks - it was picked up at some point, I have now in my records
```
Package name               | Latest     | Date       | Stable     | Date       | 
ToricVarieties             | 2021.11.17 | 17/11/2021 | 2021.01.12 | 12/01/2021 | 
```
