### ISSUE TITLE
ToricVarieties: Add `TestFile` to `PackageInfo.g` ?

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/ToricVarieties_project#185]
See https://github.com/homalg-project/homalg_project/issues/465 for motivation to do so.

Your current testfile `tst/testall.g` unfortunately can't be used as it loads `FreydCategoriesForCAP` which is not a deposited package.

**Comment by HereAround** [comment]
Thank you for pointing this out. I hope to look into this shortly.

**Comment by HereAround** [comment]
Sorry @fingolfin for this superslow response.

https://github.com/homalg-project/ToricVarieties_project/commit/2ffd5fd11462ef373415ce74aa565481fe567239 removes `FreydCategories` from the tests of the `ToricVarieties` package.

(Other non-distributed gap-packages in the `ToricVarieties_project` definitely need that package. But I believe you are here only concerned with the `ToricVarieties` package.)

In https://github.com/homalg-project/homalg_project/issues/465, you were also asking about a return value, e.g. via:
```gap
if success then
    FORCE_QUIT_GAP(0);
else
    FORCE_QUIT_GAP(1);
fi;
```
Is this change to `tst/testall.g` needed? Right now it returns `1` in case of failure, but I am not sure how `success` is being signaled. One way to find out/test things is as follows:
* I make a new release.
* You test how the gap-release handles the changes (including https://github.com/homalg-project/ToricVarieties_project/issues/190).
* We then adjust if needed.

What do you think?

**Comment by fingolfin** [comment]
My remark on the homalg-project issue is irrelevant here, as you are using `TestDirectory` and pass `exitGAP := true` which already takes care of signalling success/failure (basically by calling code equivalent to the short snippet you just posted).

Looking at https://github.com/homalg-project/ToricVarieties_project/blob/master/ToricVarieties/tst/testall.g it seems fine to me.

So, go ahead, make a release, we'll see what happens

**Comment by HereAround** [comment]
Ok. The release is here: https://github.com/homalg-project/ToricVarieties_project/releases/tag/2022-07-13

**Comment by fingolfin** [comment]
The relevant URL is really that of the `PackageInfo.g` file, i.e., https://homalg-project.github.io/ToricVarieties_project/ToricVarieties/PackageInfo.g

Unfortunately, this still does not specify a `TestFile`...

**Comment by fingolfin** [comment]
See https://github.com/homalg-project/ToricVarieties_project/pull/198

**Comment by HereAround** [comment]
Thank you. Looks good and thus merged. I also just updated the release (or do we need a new one?). Hopefully things are functional now.

**Comment by fingolfin** [comment]
Success! I've now merged this new new release into the package distribution, see https://github.com/gap-system/PackageDistro/pull/418
