### ISSUE TITLE
ToricaVarieties: broken ArchiveURL

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/ToricVarieties_project#188]
`PackageInfo.g` has `ArchiveURL` equal to https://github.com/homalg-project/ToricVarieties_project/releases/download/2022-03-23/ToricVarieties-2022.03.23 -- combined with the format suffix `.tar.gz` this results in a broken download link 

  https://github.com/homalg-project/ToricVarieties_project/releases/download/2022-03-23/ToricVarieties-2022.03.23.tar.gz

However, the actual release is missing the file extensions, i.e. no `.tar.gz` suffix, as can be seen here: https://github.com/homalg-project/ToricVarieties_project/releases/tag/2022-03-23

**Comment by fingolfin** [comment]
To fix this, no new release is necessary, just the missing tarballs needed to be provided, e.g. by re-running your release scripts or whatever.

**Comment by HereAround** [comment]
Thank you for pointing this out. Looking into this now.

**Comment by HereAround** [comment]
I have just updated the release. The link with the .tar.gz extension is now functional. @fingolfin Does this fix this issue?

**Comment by fingolfin** [comment]
The `ArchiveURL` value does not contain file extensions (and never did). Rather, the available "formats" are listed in the `ArchiveFormat` string.

**Comment by fingolfin** [comment]
It worked, thanks!
