### ISSUE TITLE
Bug in arithmetic in Serre quotients over the projective space

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/ToricVarieties_project#24]
https://github.com/homalg-project/SheafCohomologyOnToricVarieties/blob/19095784d815a9559e45a48a806b720f11a7769d/CoherentSheavesOnToricVarieties/examples/Sheaves.g#L10-L15

Then

```
IsZeroForObjects( DefiningSerreQuotientObject( sheaf ) );
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `UnderlyingMatrix' on 1 arguments at /home/kamal/software/gap/lib/methsel2.g:249 called from
UnderlyingMatrix( module 

```

**Comment by HereAround** [comment]
Please try again with the latest version. This issue should have been fixed earlier today with the following commit:

https://github.com/homalg-project/SheafCohomologyOnToricVarieties/commit/69c21a28b437bbe92a1286d8b6f2e582cdda4e4d

**Comment by kamalsaleh** [comment]
I have the lastest version, it seems you need to also adjust the line 32 in the same file.
https://github.com/homalg-project/SheafCohomologyOnToricVarieties/blob/19095784d815a9559e45a48a806b720f11a7769d/CoherentSheavesOnToricVarieties/gap/CoherentSheaves.gi#L31-L32

**Comment by HereAround** [comment]
Thanks - seems I indeed missed this before. This is fixed by https://github.com/homalg-project/SheafCohomologyOnToricVarieties/pull/25.

**Comment by kamalsaleh** [comment]
Also by the way, this line seems to contain a bug: see https://github.com/mohamed-barakat/CAP_project/commit/e2850f748c5455ccbfb9af15ac220183222a5e88

**Comment by HereAround** [comment]
Thank you. This is fixed in https://github.com/homalg-project/SheafCohomologyOnToricVarieties/pull/26.
