### ISSUE TITLE
do not call HomalgFieldOfRationalsInSingular multiple times

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/ToricVarieties_project#27]
I suggest adjusting this line
https://github.com/homalg-project/SheafCohomologyOnToricVarieties/blob/d77313a7e4bf0ca5da12fb5d68b73529f9294f97/TruncationsOfFPGradedModules/gap/LocalizedTruncations/LocalizedDegree0Ring.gi#L88

similarily to what Mohamed did in this PR
https://github.com/homalg-project/CAP_project/pull/513/commits/d8c5bae225feb93cab968421c5712471c7328665

**Comment by HereAround** [comment]
Thank you for the suggestion. This is fixed in https://github.com/homalg-project/SheafCohomologyOnToricVarieties/pull/30.
