### ISSUE TITLE
Renaming of the package -> `ToricVarieties`

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/ToricVarieties_project#28]
After merging the package `ToricVarieties` is suggest renaming this repository in `ToricVarieties`.

**Comment by HereAround** [comment]
I agree.

**Comment by HereAround** [comment]
I have proposed a merge of ToricVarieties https://github.com/homalg-project/SheafCohomologyOnToricVarieties/pull/37. Can you please review these changes?

Also, please note https://github.com/homalg-project/homalg_project/pull/334, which is an attempt to remove ToricVarieties from the homalg_project.

**Comment by mohamed-barakat** [comment]
I think you have enough access to do the renaming, correct?

**Comment by HereAround** [comment]
Yes. I have just changed the name in `ToricVarieties_project` (in the same spirit as `homalg_project` and `CAP_project`). Please close this issue if you approve.

**Comment by mohamed-barakat** [comment]
Congratulations Martin and thank you very much. The package is in best hands.
