### ISSUE TITLE
Adding ToricVarieties_project to the homalg CI and "lines of code"

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/ToricVarieties_project#41]
I have added some instructions to `homalg_project` describing how to do this: https://github.com/zickgraf/homalg_project/blob/56938ec8cb3cb681f784fea91ef751ce01702ae6/README_DEV.md

As a starting point for the tests you can look at the make targets `ci-test` and `test-with-coverage` in `ToricVarieties/makefile`, and my attempt to actually execute `ci-test` in the CI: https://github.com/zickgraf/homalg_project/commit/207dc2bb30412eedc0ed75a00a99fe699db1fc46 (the `IsPackageMarkedForLoading`-part needs https://github.com/gap-system/gap/pull/3931 to work correctly).

If anything is unclear, just ask, then maybe we can improve the instructions :-)

**Comment by HereAround** [comment]
Can this one be closed?

**Comment by zickgraf** [comment]
I don't know, are all points addressed here?

**Comment by HereAround** [comment]
We added the `ToricVarieties` packages to the test suite of the `homalg_project`. None of the other packages are tested. If you want this, we can extend the tests. If do you not want this, I believe we can close this issue.

**Comment by zickgraf** [comment]
> If you want this, we can extend the tests. If do you not want this, I believe we can close this issue.

This issue has emerged from the following comments:
* regarding tests: https://github.com/homalg-project/ToricVarieties_project/pull/37#issuecomment-646968805
* regarding "lines of code": https://github.com/homalg-project/homalg_project/pull/334#issuecomment-646131460

So as far as I am concerned you can close the issue any time you like :-)

**Comment by HereAround** [comment]
OK. I close it.
