### ISSUE TITLE
New location of distributed gap-package ToricVarieties

### ISSUE THREAD

**Issue by HereAround** [homalg-project/ToricVarieties_project#52]
@alex-konovalov: After discussion with @mohamed-barakat, we have moved the distributed gap-package ToricVarieties to this new repository. Are further adjustments necessary?

**Comment by olexandr-konovalov** [comment]
@HereAround you need to submit a PR to update the entry for this package in https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList. Note instructions in the comments in that file about the `MOVE` command, if you can't put a new `PackageInfo.g` file in the old location for automated migration.

**Comment by HereAround** [comment]
I have just opened a corresponding PR at https://github.com/gap-system/gap-distribution/pull/115.

**Comment by HereAround** [comment]
I close this issue now. We can discuss in https://github.com/homalg-project/ToricVarieties_project/issues/68 if problems remain.
