### ISSUE TITLE
QSM Explorer counting capability  

### ISSUE THREAD

**Issue by lmyreg2017** [homalg-project/ToricVarieties_project#90]
The root countings on certain polytopes (especially those polytopes with Kbar^3=30) in the QSM list are not manageable to be done by Plesken within reasonable time. We shall give a warning in the output of "CountLimitRootsOfQSM()", etc if one inputs the index of those polytopes.

**Comment by HereAround** [comment]
@lmyreg2017 : Please look at https://github.com/homalg-project/ToricVarieties_project/pull/94.
