### ISSUE TITLE
Reorder the polytopes in the database

### ISSUE THREAD

**Issue by lmyreg2017** [homalg-project/ToricVarieties_project#91]
Suggestion: we could reorder the polytopes in the database ascendingly by the triple intersection number Kbar^3.

**Comment by HereAround** [comment]
@lmyreg2017 : Please have a look at https://github.com/homalg-project/ToricVarieties_project/pull/92.

**Comment by lmyreg2017** [comment]
Great, the new database has been reordered according to the increasing of Kbar^3, thank you so much!

**Comment by HereAround** [comment]
Thank you. Merging this now.
